volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/var/www/kittygram/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - media:/var/www/kittygram/media
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/static/
      - media:/var/www/kittygram/media
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
